app/models/__init__.py
# flake8: noqa F401
from .user import User, AnonymousUser
from .post import Post
from .todo import Todo

app/models/post.py
from app import db
from sqlalchemy import ForeignKey


class Post(db.Model):
    __tablename__ = "post"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64))
    body = db.Column(db.String(500))
    user_id = db.Column(db.Integer, ForeignKey("user.id"))

    def __repr__(self):
        return f"User('{self.title}')"

app/models/todo.py
from app import db

# from sqlalchemy import ForeignKey


class Todo(db.Model):
    __tablename__ = "todo"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128))
    is_done = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

app/models/user.py
from app import db
from flask_login import UserMixin, AnonymousUserMixin


class User(db.Model, UserMixin):
    __tablename__ = "user"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(128), unique=True, nullable=False)
    password = db.Column(db.String(64), nullable=False)
    is_active = db.Column(db.Boolean, default=False)

    todos = db.relationship("Todo", backref="user")

    def __repr__(self):
        return f"User('{self.username}', '{self.password}')"


class AnonymousUser(AnonymousUserMixin):
    pass

app/forms/__init__.py
# flake8: noqa F401
from .auth import LoginForm
from .user import AddUserForm
from .todo import AddTodoForm

app/forms/auth.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    user_id = StringField("Username", [DataRequired()])
    password = PasswordField("Password", [DataRequired()])
    submit = SubmitField("Login")

app/forms/todo.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class AddTodoForm(FlaskForm):
    title = StringField("Title", [DataRequired()])
    submit = SubmitField("Add_todo")

app/forms/user.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired


class AddUserForm(FlaskForm):
    username = StringField("Username", [DataRequired()])
    password = PasswordField("Password", [DataRequired()])
    submit = SubmitField("Add_user")

app/__init__.py
import os
from dotenv import load_dotenv

from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail


load_dotenv()


app = Flask(__name__)


login_manager = LoginManager()
db = SQLAlchemy()
migration = Migrate()
mail = Mail()


def create_app(environment="development"):
    from config import config
    from app.views import (
        auth_blueprint,
        home_blueprint,
        user_blueprint,
        todo_blueprint,
        email_blueprint,
    )
    from app.models import User, AnonymousUser

    app = Flask(__name__)

    # Set app config
    env = os.environ.get("APP_ENV", environment)
    configuration = config(env)
    app.config.from_object(configuration)

    db.init_app(app)
    migration.init_app(app, db)
    login_manager.init_app(app)
    mail.init_app(app)

    app.register_blueprint(auth_blueprint)
    app.register_blueprint(home_blueprint)
    app.register_blueprint(user_blueprint)
    app.register_blueprint(todo_blueprint)
    app.register_blueprint(email_blueprint)

    @login_manager.user_loader
    def get_user(id):
        return User.query.get(int(id))

    login_manager.login_view = "auth.login"
    login_manager.login_message_category = "info"
    login_manager.anonymous_user = AnonymousUser

    return app

app/views/__init__.py
# flake8: noqa F401
from .auth import auth_blueprint
from .home import home_blueprint
from .user import user_blueprint
from .todo import todo_blueprint
from .email import email_blueprint

app/views/auth.py
from flask import Blueprint, flash, render_template, redirect, url_for, session
from flask_login import login_user, logout_user, login_required, current_user

from app.models import User
from app.forms import LoginForm

auth_blueprint = Blueprint("auth", __name__)


@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(
            User.username == form.user_id.data.lower(),
            User.password == form.password.data,
        ).first()

        if user:
            login_user(user)
            flash("Login Successful")
            return redirect(url_for("todo.index"))
    flash("Login Failed")

    return render_template("login.html", form=form)


@auth_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    session.clear()

    return redirect(url_for("home.index"))

app/views/email.py
import os
from app import mail

from flask import Blueprint, render_template, redirect, url_for
from flask_mail import Message

# MAIL_USERNAME = os.environ.get("MAIL_USERNAME")
# MAIL_PASSWORD = os.environ.get("MAIL_PASSWORD")

email_blueprint = Blueprint("email", __name__, url_prefix="/email")


@email_blueprint.route("/")
def send_email():
    msg = Message(
        "Hello",
        sender="no-replye@gmail.com",
        recipients=["andrey.berezyanskiy@gmail.com"],
    )
    # msg.body = "Hello Flask message sent from Flask-Mail"
    msg.html = render_template("email-layout.html")
    mail.send(msg)

    return render_template("email-layout.html", name="Andrii")

app/views/home.py
# from app.models import User
from flask import Blueprint, render_template

# from flask_login import login_required, current_user

home_blueprint = Blueprint("home", __name__)


@home_blueprint.route("/")
# @login_required
def index():
    # user: User = current_user
    return render_template("index.html")

app/views/todo.py
from typing import List
from app.models import Todo
from app.forms import AddTodoForm
from app.models import User
from app import db
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user

todo_blueprint = Blueprint("todo", __name__, url_prefix="/todo")


@todo_blueprint.route("/", methods=["GET", "POST"])
def index():
    form = AddTodoForm()
    user: User = current_user

    if current_user.is_authenticated:
        todos = Todo.query.order_by(Todo.id)
        todos: List[Todo] = todos.filter_by(user_id=current_user.id).all()

        if form.validate_on_submit():
            todo = Todo(title=form.title.data, user_id=user.id)

            db.session.add(todo)
            db.session.commit()
            flash("success")
            return redirect(url_for("todo.index"))

        return render_template("todo-list.html", todos=todos, form=form)

    return render_template("todo-list.html", todos=[], form=form)


# @todo_blueprint.route("/add", methods=["GET", "POST"])
# def add_todo():
#     form = AddTodoForm()
#     user: User = current_user

#     if form.validate_on_submit():
#         todo = Todo(title=form.title.data, user_id=user.id)

#         db.session.add(todo)
#         db.session.commit()
#         flash("success")
#         return redirect(url_for("todo.index"))

#     return render_template("todo-list.html", form=form)


@todo_blueprint.route("/<int:todo_id>/delete")
def delete_todo(todo_id: int):
    # user: User = current_user
    todo: Todo = Todo.query.filter(Todo.id == todo_id).first()
    db.session.delete(todo)
    db.session.commit()

    return redirect(url_for("todo.index"))

app/views/user.py
from flask import Blueprint, render_template, flash, redirect, url_for

from app.models import User
from app.forms import AddUserForm
from app import db


user_blueprint = Blueprint("user", __name__, url_prefix="/user")


@user_blueprint.route("/create", methods=["GET", "POST"])
def create():
    form = AddUserForm()
    if form.validate_on_submit():
        # TODO place is_active = true to email validation
        existing_user: User = User.query.filter(
            User.username == form.username.data
        ).first()

        if existing_user:
            flash("User already exist")
            return redirect(url_for("home.index"))

        user = User(
            username=form.username.data, password=form.password.data, is_active=True
        )

        db.session.add(user)
        db.session.commit()
        flash("User was added")
        return redirect(url_for("home.index"))

    return render_template("create-user.html", form=form)


@user_blueprint.route("/delete/<int:user_id>")
def delete_user(user_id):
    user = User.query.get_or_404(user_id, description=None)

    db.session.delete(user)
    db.session.commit()

    return "<p>user was deleted</p>"

app/templates/create-user.html
{% extends 'base.html' %}

{% block content %}
  <div class=" bg-gray-100 flex flex-col justify-center sm:py-12">
    <div class="p-10 xs:p-0 mx-auto md:w-full md:max-w-md">
      <!-- <h1 class="font-bold text-center text-2xl mb-5">Your Logo</h1>   -->
      <div class="bg-white shadow w-full rounded-lg divide-y divide-gray-200">
        <div class="px-5 py-7">
          <form role="form" action="{{ url_for('user.create') }}" method="post">
            <label class="font-semibold text-sm text-gray-600 pb-1 block">{{form.username.label}}</label>
            {{form.username(class="border rounded-lg px-3 py-2 mt-1 mb-5 text-sm w-full")}}
            <label class="font-semibold text-sm text-gray-600 pb-1 block">{{form.password.label}}</label>
            {{form.password(class="border rounded-lg px-3 py-2 mt-1 mb-5 text-sm w-full")}}
            <button type="submit" class="transition duration-200 bg-blue-500 hover:bg-blue-600 focus:bg-blue-700 focus:shadow-sm focus:ring-4 focus:ring-blue-500 focus:ring-opacity-50 text-white w-full py-2.5 rounded-lg text-sm shadow-sm hover:shadow-md font-semibold text-center inline-block">
                <span class="inline-block mr-2">Sign Up</span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4 inline-block">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
                </svg>
            </button>
          </form>
        </div>
      </div>
      <div class="py-5">
          <div class="grid grid-cols-2 gap-1">
            <div class="text-center sm:text-left whitespace-nowrap">
              <a href="{{ url_for('home.index')  }}" class="transition duration-200 mx-5 px-5 py-4 cursor-pointer font-normal text-sm rounded-lg text-gray-500 hover:bg-gray-200 focus:outline-none focus:bg-gray-300 focus:ring-2 focus:ring-gray-400 focus:ring-opacity-50 ring-inset">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4 inline-block align-text-top">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                  </svg>
                  <span class="inline-block ml-1">Back</span>
                </a>
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock%}

app/templates/email-layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body style="margin:0; padding:0;word-spacing:normal;">
  <div role="article" aria-roledescription="email" lang="en" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;">
    <table role="presentation" style="width:100%;border:none;border-spacing:0;">
      <tr>
        <td align="center" style="padding:0;">
          <table role="presentation" style="width:94%; max-width:600px; border: none; border-spacing: 0; text-align: left; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 20px;line-height: 24px;">
            <tr>
              <td>
                <a href="http://google.com/" style="text-decoration: none;">
                  <img src="../static/img/logo.svg" alt="Logo">
                </a>
              </td>
            </tr>
            <tr>
              <td style="padding: 30px 30px 15px; background-color: #80ae97; background-image: url(../static/img/background.png);">
                <h1 style="margin-bottom: 50px; font-size: 50px; line-height: 62px; font-weight: bold; ">
                  Welcome to UGS, <br> {{ name }}!
                </h1>
                <p>
                  We are University Graphic Systems, a student-run and operated print service located on Cal Poly’s campus.
                </p>
              </td>
            </tr>
            <tr>
              <td style="padding: 0;">
                <h3 style="margin-bottom: 30px; font-size: 35px; font-weight: bold;">
                  About Our Shop
                </h3>
                <p>
                  UGS offers a number of template designs, t-shirts, and stickers! All of these products are available in our storefront, email us at ugs@calpoly.edu about availability of these products or if you have any questions.
                </p>
              </td>
            </tr>
            <tr>
              <td>
                <table role="presentation" width="100%">
                  <tr>
                    <td>
                      <img src="../static/img/img1.png" alt="">
                    </td>
                    <td>
                      <h3>
                        Resume
                      </h3>
                      <p>
                        Eight unique resume templates available. Templates cost $15 plus the cost of printing, see our services page for pricing.
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <h3>
                        Business Cards
                      </h3>
                      <p>
                        Eight unique templates available. Templates cost $15 plus the cost of printing, see our services page for pricing. 
                      </p>
                    </td>
                    <td>
                      <img src="../static/img/img2.png" alt="">
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td>
                <a href="https://facebokk.com" style="width: 190px; height: 43px; text-decoration: none; background-color: #154734; color: #fff;"> View Our Shop</a>
              </td>
            </tr>
            <tr>
              <td style="padding: 29px 145px; font-size: 15px; background-color: #e5e5e5;">
                <div>
                  <img src="../static/img/logo-instagram.svg" alt="">
                  <img src="../static/img/logo-facebook.svg" alt="">
                  <img src="../static/img/logo-linkedin.svg" alt="">
                </div>
                <p>www.ugs.com</p>
                <p style="margin-bottom: 20px;">8050809</p>
                <p>Building 26, Room 212A</p>
                <p>San Luis, CA 93405</p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% import 'header.html' as base_header with context %}


{% block header %}
  {{ base_header }}
{% endblock %}

{% block content %}
  <h1>Home Page</h1>

  <!-- {% if current_user.is_authenticated %}
    <div class="h-100 w-full flex items-center justify-center bg-teal-lightest font-sans">
      <div class="bg-text-gray-700 rounded shadow p-6 m-4 w-full lg:w-3/4 lg:max-w-lg">
            <div class="mb-4">
                <h1 class="text-grey-darkest">Todo List</h1>
                <div class="flex mt-4">
                    <input class="shadow appearance-none border rounded w-full py-2 px-3 mr-4 text-grey-darker" placeholder="Add Todo">
                    <button class="flex-no-shrink p-2 border-2 rounded text-teal border-teal hover:text-white hover:bg-teal">Add</button>
                </div>
            </div>
            <div>
                <div class="flex mb-4 items-center">
                    <p class="w-full text-grey-darkest">Add another component to Tailwind Components</p>
                    <button class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-green border-green hover:bg-green">Done</button>
                    <button class="flex-no-shrink p-2 ml-2 border-2 rounded text-red border-red hover:text-white hover:bg-red">Remove</button>
                </div>
                <div class="flex mb-4 items-center">
                    <p class="w-full line-through text-green">Submit Todo App Component to Tailwind Components</p>
                    <button class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-grey border-grey hover:bg-grey">Not Done</button>
                    <button class="flex-no-shrink p-2 ml-2 border-2 rounded text-red border-red hover:text-white hover:bg-red">Remove</button>
                </div>
            </div>
        </div>
    </div>
  {% endif%} -->
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <div class=" bg-gray-100 flex flex-col justify-center sm:py-12">
    <div class="p-10 xs:p-0 mx-auto md:w-full md:max-w-md">
      <!-- <h1 class="font-bold text-center text-2xl mb-5">Your Logo</h1>   -->
      <div class="bg-white shadow w-full rounded-lg divide-y divide-gray-200">
        <div class="px-5 py-7">
          <form role="form" action="{{ url_for('auth.login') }}" method="post">
            <label class="font-semibold text-sm text-gray-600 pb-1 block">{{form.user_id.label}}</label>
            {{form.user_id(class="border rounded-lg px-3 py-2 mt-1 mb-5 text-sm w-full")}}
            <label class="font-semibold text-sm text-gray-600 pb-1 block">{{form.password.label}}</label>
            {{form.password(class="border rounded-lg px-3 py-2 mt-1 mb-5 text-sm w-full")}}
            <button type="submit" class="transition duration-200 bg-blue-500 hover:bg-blue-600 focus:bg-blue-700 focus:shadow-sm focus:ring-4 focus:ring-blue-500 focus:ring-opacity-50 text-white w-full py-2.5 rounded-lg text-sm shadow-sm hover:shadow-md font-semibold text-center inline-block">
                <span class="inline-block mr-2">Login</span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4 inline-block">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
                </svg>
            </button>
          </form>
        </div>
      </div>
      <div class="py-5">
          <div class="grid grid-cols-2 gap-1">
            <div class="text-center sm:text-left whitespace-nowrap">
              <a href="{{ url_for('home.index')  }}" class="transition duration-200 mx-5 px-5 py-4 cursor-pointer font-normal text-sm rounded-lg text-gray-500 hover:bg-gray-200 focus:outline-none focus:bg-gray-300 focus:ring-2 focus:ring-gray-400 focus:ring-opacity-50 ring-inset">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4 inline-block align-text-top">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                  </svg>
                  <span class="inline-block ml-1">Back</span>
                </a>
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}

app/templates/todo-list.html
{%  extends 'base.html' %}

{% block content %}
    <!-- component -->
    <div class="w-full flex items-center justify-center bg-slate-400 font-sans">
        <div class="bg-slate-700 rounded shadow p-6 m-4 w-full lg:w-3/4 .max-w-screen-md">
            <div class="mb-4">
                <h1 class="text-grey-darkest">Todo List</h1>
                <div class="flex mt-4">
                    <form class="flex mt-4" role="form" action="{{ url_for('todo.index') }}" method="post">
                        <!-- <input class="shadow appearance-none border rounded w-full py-2 px-3 mr-4 text-grey-darker" placeholder="Add Todo"> -->
                    {{form.title(class="shadow appearance-none border rounded w-full py-2 px-3 mr-4 text-grey-darker")}}
                    <button class="flex-no-shrink p-2 border-2 rounded text-teal border-teal hover:text-white hover:bg-teal">Add</button>
                    </form>
                </div>
            </div>
            <div>
                {% for todo in todos %}
                    <div class="flex mb-4 items-center">
                        <p class="w-full text-grey-darkest">{{ todo.title }}</p>
                        <a href="{{ url_for('home.index')}}" class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-grey border-grey hover:bg-grey">Not Done</a>
                        <a  href="{{ url_for('todo.delete_todo', todo_id=todo.id )}}" class="flex-no-shrink p-2 ml-2 border-2 rounded text-red border-red hover:text-white hover:bg-red">Remove</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
  <div class=" bg-gray-100 flex flex-col justify-center sm:py-12">
    <div class="p-10 xs:p-0 mx-auto md:w-full md:max-w-md">
      <h1 class="font-bold text-center text-2xl mb-5">Your Logo</h1>  
      <div class="bg-white shadow w-full rounded-lg divide-y divide-gray-200">
        <div class="px-5 py-7">
          <form role="form" action="{{ url_for('login') }}" method="post">
            <label class="font-semibold text-sm text-gray-600 pb-1 block">{{form.user_id.label}}</label>
            {{form.user_id(class="border rounded-lg px-3 py-2 mt-1 mb-5 text-sm w-full")}}
            <label class="font-semibold text-sm text-gray-600 pb-1 block">{{form.password.label}}</label>
            {{form.password(class="border rounded-lg px-3 py-2 mt-1 mb-5 text-sm w-full")}}
            <button type="submit" class="transition duration-200 bg-blue-500 hover:bg-blue-600 focus:bg-blue-700 focus:shadow-sm focus:ring-4 focus:ring-blue-500 focus:ring-opacity-50 text-white w-full py-2.5 rounded-lg text-sm shadow-sm hover:shadow-md font-semibold text-center inline-block">
                <span class="inline-block mr-2">Login</span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4 inline-block">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
                </svg>
            </button>
          </form>
        </div>
      </div>
      <div class="py-5">
          <div class="grid grid-cols-2 gap-1">
            <div class="text-center sm:text-left whitespace-nowrap">
              <button class="transition duration-200 mx-5 px-5 py-4 cursor-pointer font-normal text-sm rounded-lg text-gray-500 hover:bg-gray-200 focus:outline-none focus:bg-gray-300 focus:ring-2 focus:ring-gray-400 focus:ring-opacity-50 ring-inset">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4 inline-block align-text-top">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                  </svg>
                  <span class="inline-block ml-1">Back</span>
              </button>
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}